### ISSUE TITLE
Bcrypt does not use hash parameter

### ISSUE THREAD

**Issue by user9209** [Password4j/password4j#18]
**Describe the bug**
Correcy bcrypt hash failed to be verified.

**To Reproduce**
Call:
```
String hash = "$2b$12$fRnFJP6V1PybWlgvGYYeEutnpgtmYPBy94UPwpKfH2J5GbxA22cFC";
String password = "1234";
boolean verified = Password.check(password, hash).withBCrypt();
```

`verified` is false!

**Expected behavior**
`verified` should be true!

**Environment:**
 - OS: Windows 10 2011
 - JDK 11
 - Version group: 'com.password4j', name: 'password4j', version: '1.4.0'

**Workaround**
```
char minor = passwordHash.charAt(2);
String rounds = passwordHash.replaceFirst("\\$.{2}\\$([0-9]+)\\$.*", "$1");
boolean verified = Password.check(password,passwordHash).with(BCryptFunction.getInstance(com.password4j.BCrypt.valueOf(minor), Integer.parseInt(rounds)));
```

**Comment by firaja** [comment]
Hi @user9209,
thank you for your contribution! 🎉 

From the documentation of `#withBCrypt()`:

> This method reads the configurations in the `psw4j.properties` file. If no configuration is found, then the default parameters are used.

That's because the String `hash` you are checking with `#check()` should be produced by this library via `#hash()`: `#hash()` and `#check()` always use the same parameters.

In your scenario the String `hash` is produced by a third-party library, am I right? If you want to migrate passwords generated from a third-party library you can check method `#update()`, otherwise please describe your scenario so we can manage it for example in a different method. 

Thank you! 💯

**Comment by user9209** [comment]
Often password databases contain passwords with different rounds as administrator increase the count in over the time.
As users password hashes will not or only updated when setting a new password a check should always work with any valid incomming password hash.
I do not see any case there it is usefull that the check is failling when the hash is ok.

Here: It is realy confusing, that a valid bcrypt hash is verified as invalid.
An exception that the hash is not supported would be ok.

In my case, generating hashes with your and a third party lib was successfull.
Verifing the hash with the third party was ok, your was failing. As the function is taking a String how should the developper know if the String has 10 or 12 rounds. I used your #hash() with modified rounds.

The ideal would be that #verify(<password>,<hash>) would detect any valid hashes and verify it. So hash can be e.g. Bcrypt, PBKDF2 or SCrypt.

**Comment by firaja** [comment]
The scenario you are describing is covered by the `#update()` method:

```java
String password = "...";
String hash = retrieveFromDB(); // hash with old configurations

HashUpdate update = Password.check(password, hash).update().withBCrypt(); // BCrypt uses new configurations
if(update.isVerified())
{
    Hash newHash = update.getHash(); // verified and generated a new hash with new configurations
    storeToDB(newHash);
}
```

Or if you don't want to calculate the new hash and you want to just verify it:
```java
boolean verified = Password.check(password, hash)
                           .with(BCryptFunction.getInstanceFromHash(hash))
                           .isVerified();
```

Any `HashingFunction` hash a method `#getInstanceFromHash()`, if the underlying function supports it (e.g. PBKDF2 does not support it).

The problem is the lack of documentation here on GitHub (and lack of time to maintain it), but you can find the javadoc [here](https://javadoc.io/doc/com.password4j/password4j/latest/index.html).

Let me know if this solution fit your needs.

**Comment by user9209** [comment]
Thank you for the information.

This solution is fine. Thanks a lot.

If you like you can close my pull request.
